# Site settings
title: ssplatt.github.io
email: sweet.brett@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ssplatt is Brett Taylor. This is a page for his Github projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ssplatt.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  ssplatt

# Build settings
markdown: kramdown
